on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: 1.2.5
          terraform_wrapper: false
      - run: |
          terraform init
          terraform validate
        working-directory: examples/
