on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: iam,sts,sns
          DEFAULT_REGION: eu-west-2
        ports:
          - 4566:4566
          - 4571:4571
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.13

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.x
          terraform_wrapper: false

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - name: Run Go Tests
        working-directory: test
        run: go test -v
